project_id = "pecnrqvrennoqvewkpuq"

[functions.ingest]
verify_jwt = false

[functions.projects-create]
verify_jwt = false

[functions.projects-list]
verify_jwt = false

[functions.create-demo-project]
verify_jwt = false

[functions.analyze-drift]
verify_jwt = false

[functions.upload-dataset]
verify_jwt = false

[functions.ingest-llm-interaction]
verify_jwt = false

[functions.ingest-embeddings]
verify_jwt = false

[functions.ingest-event]
verify_jwt = false

[functions.api-keys-create]
verify_jwt = false

[functions.api-keys-list]
verify_jwt = false

[functions.api-keys-revoke]
verify_jwt = false
